var softSkills = [
    { name: "ativo" },
    { name: "profissional" },
    { name: "lógico" },
    { name: "completo" },
    { name: "responsável" },
    { name: "inovação" },
    { name: "construção" },
    { name: "autonomia" },
    { name: "responsabilidade" },
    { name: "flexível" },
    { name: "colaborativo" },
    { name: "tato" },
    { name: "afiado" },
    { name: "disciplina" },
    { name: "desafiador" },
    { name: "disponibilidade" },
    { name: "inteligente" },
    { name: "eficiente" },
    { name: "líder" },
    { name: "positivo" },
    { name: "criatividade" },
    { name: "independente" },
    { name: "treinamento" },
    { name: "criativo" },
    { name: "proativo" },
    { name: "maneira" },
    { name: "trabalho em equipe" },
    { name: "comprometido" },
    { name: "escrever" },
    { name: "organizado" },
    { name: "empreendedor" },
    { name: "paixão" },
    { name: "ação orientada" },
    { name: "vontade de aprender" },
    { name: "motivado" },
    { name: "comprometimento" },
    { name: "energia" },
    { name: "iniciativa" },
    { name: "curioso" },
    { name: "analítico" },
    { name: "atento" },
    { name: "critério" },
    { name: "preciso" },
    { name: "compreensão" },
    { name: "comunicativo" },
    { name: "flexibilidade" },
    { name: "produtivo" },
    { name: "consistente" },
    { name: "empatia" },
    { name: "Liderança" },
    { name: "pronto" },
    { name: "articular" },
    { name: "fidelidade" },
    { name: "prático" },
    { name: "tomar decisões" },
    { name: "agradável" },
    { name: "apresentação" },
    { name: "talentoso" },
    { name: "verbal e escrita" },
    { name: "inspirado" },
    { name: "paciente" },
    { name: "habilidades de comunicação" },
    { name: "atenção aos detalhes" },
    { name: "atenção aos detalhes" },
    { name: "competitivo" },
    { name: "ético" },
    { name: "integridade" },
    { name: "pontual" },
    { name: "maturidade" },
    { name: "motivação" },
    { name: "animado" },
    { name: "capacidade de comunicação" },
    { name: "cronograma" },
    { name: "humor" },
    { name: "dedicação" },
    { name: "legais" },
    { name: "organizacional" },
    { name: "bem organizado" },
    { name: "entusiasmo" },
    { name: "habilidades analíticas" },
    { name: "mente aberta" },
    { name: "capaz de se comunicar" },
    { name: "Espírito de equipe" },
    { name: "versatilidade" },
    { name: "confiante" },
    { name: "confiável" },
    { name: "Disponibilidade para viagens" },
    { name: "eficácia" },
    { name: "habilidades de programação" },
    { name: "pensamento crítico" },
    { name: "respeitoso" },
    { name: "seja criativo" },
    { name: "visão estratégica" },
    { name: "atento aos detalhes" },
    { name: "bom senso" },
    { name: "capacidade de aprender" },
    { name: "capacidade de vender" },
    { name: "dedicada" },
    { name: "entusiasmado" },
    { name: "habilidades de liderança" },
    { name: "habilidades organizacionais" },
    { name: "honestidade" },
    { name: "Inovativa" },
    { name: "pessoa responsável" },
    { name: "planejamento estratégico" },
    { name: "tolerante" },
    { name: "ambicioso" },
    { name: "assertividade" },
    { name: "atitude positiva" },
    { name: "calma" },
    { name: "capacidade de adaptação" },
    { name: "cortesia" },
    { name: "detalhado" },
    { name: "gerenciamento de equipe" },
    { name: "habilidades interpessoais" },
    { name: "habilidades para resolver problemas" },
    { name: "paciência" },
    { name: "pontualidade" },
    { name: "precisão" },
    { name: "simpatia" },
    { name: "Solução de problemas" },
    { name: "solucionador de problema" },
    { name: "aconselhamento" },
    { name: "alcançar seus objetivos" },
    { name: "capacidade de analisar" },
    { name: "capacidade de interagir" },
    { name: "capacidade de priorizar" },
    { name: "conceituação" },
    { name: "disciplinado" },
    { name: "educado" },
    { name: "Gerenciamento de Projetos" },
    { name: "gerenciamento de tempo" },
    { name: "habilidades de análise" },
    { name: "habilidades de comunicação interpessoal" },
    { name: "Habilidades de gestão de tempo" },
    { name: "maduro" },
    { name: "membro da equipe" },
    { name: "negociador" },
    { name: "pensamento criativo" },
    { name: "pensamento inovador" },
    { name: "pessoa dinâmica" },
    { name: "profissionalismo" },
    { name: "relações humanas" },
    { name: "sensibilidade" },
    { name: "senso de responsabilidade" },
    { name: "tolerância" },
    { name: "tomar iniciativa" },
    { name: "trabalhador" },
    { name: "trabalhar bem em equipe" },
    { name: "trabalhar de forma colaborativa" },
    { name: "visão de futuro" }
];