var softSkills = [
    { name: "a ler e escrever" },
    { name: "aberta à mudança" },
    { name: "abordagem criativa" },
    { name: "abordagem criativa céu azul" },
    { name: "abordagem criativa e inovadora" },
    { name: "abordagem o trabalho em equipe" },
    { name: "abordagem pró-ativa" },
    { name: "abordagem trabalho em equipe" },
    { name: "abrir a uma mudança" },
    { name: "absenceable para se comunicar" },
    { name: "ação orientada" },
    { name: "aconselhamento" },
    { name: "administra próprio tempo de forma eficaz" },
    { name: "administrar o departamento" },
    { name: "administrar o departamento cozinha movimentada" },
    { name: "afiado" },
    { name: "afirmativo" },
    { name: "agradável" },
    { name: "agressivo" },
    { name: "alcançar metas desafiadoras" },
    { name: "alcançar os objetivos da empresa" },
    { name: "alcançar seus objetivos" },
    { name: "alcançar seus próprios objetivos" },
    { name: "alvo iniciativa orientada" },
    { name: "amadurecer personalidade independente" },
    { name: "ambicioso" },
    { name: "amigável personalidade profissional" },
    { name: "análise e habilidades de resolução de problemas" },
    { name: "analítica analítica" },
    { name: "analítico" },
    { name: "animado" },
    { name: "ansioso para aprender" },
    { name: "aprenda rapidamente" },
    { name: "aprender habilidades de deficiência" },
    { name: "Aprendiz rápido" },
    { name: "Aprendizagem autônoma" },
    { name: "aprendizagem directiva auto" },
    { name: "aprendizagem e habilidades" },
    { name: "Aprendizagem rapida" },
    { name: "aprendizagem solvingquick" },
    { name: "apresentação" },
    { name: "apresentação profissional" },
    { name: "apresentável" },
    { name: "articular" },
    { name: "assertividade" },
    { name: "assertivo" },
    { name: "atenção aos detalhes" },
    { name: "atenção aos detalhes" },
    { name: "atendimento ao cliente equipa orientada" },
    { name: "atento" },
    { name: "atento aos detalhes" },
    { name: "atingir metas" },
    { name: "atitude de resolução de problemas" },
    { name: "atitude disciplinedprofessional" },
    { name: "atitude positiva" },
    { name: "atitude positiva cando" },
    { name: "Atitude profissional" },
    { name: "ativo" },
    { name: "ativo pessoalmente" },
    { name: "atributos pessoais excelente gestão e habilidades de liderança" },
    { name: "auto aprendizado" },
    { name: "auto arranque com a iniciativa" },
    { name: "auto boas motivado habilidades organizacionais" },
    { name: "auto confiança" },
    { name: "auto directeddirected" },
    { name: "auto gestão confiante" },
    { name: "auto habilidades organizacionais" },
    { name: "auto impulsionado" },
    { name: "auto motivado" },
    { name: "auto motivatedself" },
    { name: "auto starters" },
    { name: "auto-aprendizagem" },
    { name: "auto-confiança e iniciativa" },
    { name: "auto-confiante" },
    { name: "auto-consciência" },
    { name: "auto-dirigida" },
    { name: "auto-gestão e habilidades organizacionais" },
    { name: "auto-motivação" },
    { name: "auto-motivação e iniciativa" },
    { name: "auto-motivado e conduzido" },
    { name: "auto-motivado e organizado" },
    { name: "autonomia" },
    { name: "avaliação e relatórios corretos" },
    { name: "bem organizado" },
    { name: "Boa capacidade de comunicação de personalidade" },
    { name: "bom senso" },
    { name: "calma" },
    { name: "calmamente trabalho em um de alta pressão" },
    { name: "caloroso" },
    { name: "capabilitiesability organizacional" },
    { name: "capacidade competências gerenciais" },
    { name: "capacidade de adaptação" },
    { name: "capacidade de ampliar a venda" },
    { name: "capacidade de analisar" },
    { name: "capacidade de antecipação" },
    { name: "capacidade de aprender" },
    { name: "capacidade de aprender continuamente" },
    { name: "capacidade de aprender e adaptar" },
    { name: "capacidade de compilar um relatório" },
    { name: "capacidade de comprar e vender" },
    { name: "capacidade de comunicação" },
    { name: "capacidade de comunicação escrita" },
    { name: "capacidade de conceituar" },
    { name: "capacidade de coordenar" },
    { name: "capacidade de estimular cooperação " },
    { name: "capacidade de fazer venda personalizada" },
    { name: "capacidade de gerir" },
    { name: "capacidade de gerir e organizar" },
    { name: "capacidade de interagir" },
    { name: "capacidade de interpretar" },
    { name: "capacidade de ler e interpretar" },
    { name: "capacidade de liderar e coordenar" },
    { name: "capacidade de motivar" },
    { name: "capacidade de navegar e gerenciar" },
    { name: "capacidade de negociar" },
    { name: "capacidade de obter e analisar" },
    { name: "capacidade de organização e priorização" },
    { name: "capacidade de organizar" },
    { name: "capacidade de ouvir" },
    { name: "capacidade de persuadir" },
    { name: "capacidade de planejar" },
    { name: "capacidade de planejar e priorizar" },
    { name: "capacidade de presente e relatório" },
    { name: "capacidade de priorizar" },
    { name: "capacidade de promover a cooperação" },
    { name: "capacidade de relatar" },
    { name: "capacidade de vender" },
    { name: "capacidade de viajar" },
    { name: "capacidade e vontade de viagem" },
    { name: "capacidade gerencial" },
    { name: "capacidade habilidades de liderança" },
    { name: "capacidade habilidades gerenciais" },
    { name: "capacidade para priorização eficiente" },
    { name: "capacidade traços competenciesleadership" },
    { name: "capacidades administrativas" },
    { name: "capacidades organizacionais" },
    { name: "capaz de executar múltiplas tarefas simultâneas e priorizar" },
    { name: "capaz de gerenciar e priorizar" },
    { name: "capaz de influenciar e persuadir" },
    { name: "capaz de persuadir" },
    { name: "capaz de priorizar" },
    { name: "capaz de realizar multiplas tarefas simultanêas" },
    { name: "capaz de se comunicar" },
    { name: "Cliente orientado" },
    { name: "colaborativo" },
    { name: "comercialização fortes habilidades de comunicação" },
    { name: "competências através da participação na formação onthejob" },
    { name: "competências de inovação" },
    { name: "competências interculturais" },
    { name: "competências linguísticas Inglês orais" },
    { name: "competências-chave de pensamento criativo" },
    { name: "competências-chave de treinamento" },
    { name: "competitivo" },
    { name: "completo" },
    { name: "compreensão" },
    { name: "compreensão compreensão" },
    { name: "comprometido" },
    { name: "comprometimento" },
    { name: "comprometimento da equipe" },
    { name: "compromisso com a responsabilidade" },
    { name: "compromisso com o trabalho" },
    { name: "compromisso com o trabalho em equipe" },
    { name: "compromisso com prestação de contas" },
    { name: "comunicação e habilidades de escrita" },
    { name: "comunicador" },
    { name: "comunicando habilidades" },
    { name: "comunicar facilmente" },
    { name: "comunicativo" },
    { name: "comunicável" },
    { name: "conceituação" },
    { name: "confiante" },
    { name: "confiante e dinâmica personalidade" },
    { name: "confiável" },
    { name: "conflito de gestão" },
    { name: "conhecimentos de informática" },
    { name: "conhecimentos de informática e pensamento analítico" },
    { name: "consciência política" },
    { name: "consistente" },
    { name: "consolidação de equipe" },
    { name: "construção" },
    { name: "construindo assertividade" },
    { name: "construtor da equipe" },
    { name: "construtor de relacionamento" },
    { name: "construtor de relacionamento relacionamento" },
    { name: "consultoria habilidades" },
    { name: "coordenação habilidades" },
    { name: "coordenada" },
    { name: "coordenar todas as habilidades de teste" },
    { name: "cortês" },
    { name: "cortesia" },
    { name: "criatividade" },
    { name: "criatividade e pensamento analítico" },
    { name: "criatividade e visão de futuro" },
    { name: "criatividade no pensamento" },
    { name: "criativo" },
    { name: "criativo na sua abordagem" },
    { name: "critério" },
    { name: "cronograma" },
    { name: "cumprimento de prazos" },
    { name: "cumprimento de prazos de pagamento semanais" },
    { name: "curioso" },
    { name: "curiousan" },
    { name: "de tato" },
    { name: "de trabalho em um de alta pressão" },
    { name: "dedicação" },
    { name: "dedicação à qualidade" },
    { name: "dedicação à qualidade da escrita" },
    { name: "dedicação e unidade para proporcionar qualidade" },
    { name: "dedicada" },
    { name: "desafiador" },
    { name: "desafiante campeão" },
    { name: "desenvolvimento de competências" },
    { name: "desenvolvimento de competências de relacionamento com clientes" },
    { name: "desenvolvimento excelentes habilidades de comunicação" },
    { name: "detalhado" },
    { name: "diligência" },
    { name: "diligente" },
    { name: "dinâmica pessoa de vendas" },
    { name: "dinâmico e pessoa pró-ativa" },
    { name: "diplomacia" },
    { name: "diplomacia e habilidades interpessoais" },
    { name: "diplomático" },
    { name: "dirigido" },
    { name: "disciplina" },
    { name: "disciplinado" },
    { name: "disponibilidade" },
    { name: "Disponibilidade para viagens" },
    { name: "disposição para ouvir" },
    { name: "disposto a viajar" },
    { name: "draftspersonnegotiator" },
    { name: "duro pessoa de vendas de trabalho" },
    { name: "edifício da equipe e habilidades interpessoais" },
    { name: "educacional e habilidades sociais" },
    { name: "educado" },
    { name: "eficácia" },
    { name: "eficiente" },
    { name: "elaboração de propostas" },
    { name: "empatia" },
    { name: "empreendedor" },
    { name: "energia" },
    { name: "energia energia brokerageenergy energia sectorenergy" },
    { name: "enérgico" },
    { name: "entusiasmado" },
    { name: "entusiasmo" },
    { name: "entusiasta indivíduo interessado em aprender" },
    { name: "entusiástica personalidade enérgica" },
    { name: "entusiástico e disposto a aprender" },
    { name: "equipa que irá trabalhar" },
    { name: "equipe com um compromisso" },
    { name: "equipe de edifício" },
    { name: "equipe demonstrar um compromisso" },
    { name: "equipe e um compromisso" },
    { name: "equipe excelente gestão do tempo e habilidades de priorização" },
    { name: "equipe habilidades de interação trabalhos por encomenda" },
    { name: "equipe habilidades de negociação de trabalho" },
    { name: "equipe para garantir o compromisso" },
    { name: "equipe que trabalho genuinamente" },
    { name: "equipe s interação com o cliente" },
    { name: "escrever" },
    { name: "Espírito de equipe" },
    { name: "estudantes entusiastas ansioso para aprender" },
    { name: "ética de serviço ao cliente" },
    { name: "Ética de trabalho" },
    { name: "éticas profissionais" },
    { name: "ético" },
    { name: "executar e desenvolver o departamento" },
    { name: "executar o departamento de manutenção" },
    { name: "extrovertido" },
    { name: "facilitação e consultoria habilidades" },
    { name: "facilitação e habilidades de coaching" },
    { name: "facilitação e habilidades que influenciam" },
    { name: "facilitando habilidades" },
    { name: "facilitando habilidades de reunião" },
    { name: "falar em público" },
    { name: "feedback construtivo" },
    { name: "feedback construtivo e pró-ativa" },
    { name: "fidelidade" },
    { name: "flexibilidade" },
    { name: "flexibilityteamwork" },
    { name: "flexível" },
    { name: "flexível com as horas de trabalho" },
    { name: "flexível com hora" },
    { name: "flexível no que diz respeito a hora" },
    { name: "focado nos detalhes" },
    { name: "foco no cliente auto-desenvolvimento e habilidades interpessoais" },
    { name: "followthrough" },
    { name: "forma de telefone profissional" },
    { name: "forma diplomática" },
    { name: "forma diplomática e positiva" },
    { name: "forma profissional e articulada" },
    { name: "forma sistemática e controlada" },
    { name: "forma sistemática e estruturada" },
    { name: "forma sistemática e metódica" },
    { name: "forma sistemática e organizada" },
    { name: "forma sistemática e profissional" },
    { name: "forma telefone cortês" },
    { name: "formação para actualização de competências" },
    { name: "fundo inovação e habilidades" },
    { name: "gere o tempo de forma eficaz" },
    { name: "gerenciamento de equipe" },
    { name: "gerenciamento de linha de especificação pessoal" },
    { name: "Gerenciamento de Projetos" },
    { name: "gerenciamento de tarefas" },
    { name: "gerenciamento de tempo" },
    { name: "gerenciamento diário pessoal" },
    { name: "gerenciamento e execução de tarefas" },
    { name: "gerenciamento pessoal" },
    { name: "gerenciar as tarefas" },
    { name: "gerenciar múltiplas tarefas" },
    { name: "gerenciar múltiplos projetos e tarefas" },
    { name: "gerenciar várias tarefas" },
    { name: "gerente de contas entusiasmado para aprender" },
    { name: "gestão de despesas de pessoal" },
    { name: "gestão de pessoal e habilidades de liderança" },
    { name: "gestão de Pessoas" },
    { name: "gestão do tempo pessoal" },
    { name: "gestão e atribuição de tarefas" },
    { name: "gestão e vendas habilidade" },
    { name: "Habilidade de gerenciamento" },
    { name: "habilidade de liderança" },
    { name: "Habilidade em comunicação" },
    { name: "habilidades analíticas" },
    { name: "habilidades analíticas e escritas" },
    { name: "habilidades analíticas e numéricas" },
    { name: "habilidades auditivas" },
    { name: "habilidades c de desenvolvimento orientado a objetos" },
    { name: "habilidades capacidade de comunicar" },
    { name: "habilidades collaborationcooperation" },
    { name: "habilidades com capacidade de comunicar" },
    { name: "habilidades conceituais" },
    { name: "habilidades da equipe de trabalho" },
    { name: "habilidades de aconselhamento" },
    { name: "habilidades de advocacia" },
    { name: "habilidades de análise" },
    { name: "habilidades de aprendizagem e de pensamento" },
    { name: "habilidades de aprendizagem rápidas" },
    { name: "habilidades de apresentação" },
    { name: "habilidades de comunicação" },
    { name: "habilidades de comunicação de telefone" },
    { name: "habilidades de comunicação e interpessoais" },
    { name: "habilidades de comunicação e organizacionais" },
    { name: "habilidades de comunicação interpessoal" },
    { name: "habilidades de comunicação oral" },
    { name: "habilidades de comunicação verbal" },
    { name: "habilidades de comunicação verbaltelephone" },
    { name: "habilidades de conceituação" },
    { name: "habilidades de construção de equipe" },
    { name: "habilidades de coordenação" },
    { name: "habilidades de delegação" },
    { name: "habilidades de diplomacia" },
    { name: "habilidades de diplomacia e coordenação" },
    { name: "habilidades de escrita" },
    { name: "habilidades de escrita proposta" },
    { name: "habilidades de escuta e comunicação" },
    { name: "habilidades de escuta e de questionamento" },
    { name: "habilidades de experiência em treinamento" },
    { name: "habilidades de facilitação" },
    { name: "habilidades de facilitação e de apresentação" },
    { name: "habilidades de facilitação e negociação" },
    { name: "habilidades de falar em público" },
    { name: "habilidades de faturamento do cliente" },
    { name: "habilidades de gerenciamento de competências de gestão" },
    { name: "habilidades de gerenciamento de engajamento da equipe" },
    { name: "habilidades de gerenciamento de equipe" },
    { name: "habilidades de gerenciamento de gestão e habilidades de comunicação" },
    { name: "habilidades de gerenciamento de habilidades de apresentação" },
    { name: "habilidades de gerenciamento de memória" },
    { name: "habilidades de gerenciamento de pessoal" },
    { name: "habilidades de gerenciamento de projetos" },
    { name: "habilidades de gerenciamento de tempo pessoal" },
    { name: "habilidades de gestão de conflitos" },
    { name: "habilidades de gestão de pessoal" },
    { name: "habilidades de gestão de pessoas" },
    { name: "Habilidades de gestão de tempo" },
    { name: "habilidades de interação da equipe" },
    { name: "habilidades de interpretação" },
    { name: "habilidades de julgamento" },
    { name: "habilidades de liderança" },
    { name: "habilidades de liderança e delegação" },
    { name: "habilidades de liderança e gestão" },
    { name: "habilidades de linguagem" },
    { name: "habilidades de manuseio de cliente" },
    { name: "habilidades de marketing" },
    { name: "habilidades de marketing e divulgação" },
    { name: "Habilidades de mentoria e treinamento" },
    { name: "habilidades de mídia social" },
    { name: "Habilidades de motivacionais e de treinamento" },
    { name: "habilidades de negociação e comunicação" },
    { name: "habilidades de negociação e diplomacia" },
    { name: "habilidades de negociação e fechamento" },
    { name: "Habilidades de organização" },
    { name: "habilidades de organização e comunicação" },
    { name: "habilidades de orientação ao cliente" },
    { name: "habilidades de orientação de serviço ao cliente" },
    { name: "habilidades de pensamento analítico" },
    { name: "habilidades de pensamento analítico e criativo" },
    { name: "habilidades de pensamento analítico e crítico" },
    { name: "habilidades de pensamento conceitual" },
    { name: "habilidades de pensamento crítico" },
    { name: "habilidades de pesquisa" },
    { name: "habilidades de pesquisa e análise" },
    { name: "habilidades de pessoas" },
    { name: "habilidades de planejamento" },
    { name: "habilidades de planejamento e organização" },
    { name: "habilidades de planejamento e organizacionais" },
    { name: "habilidades de priorização" },
    { name: "habilidades de priorização e organização" },
    { name: "habilidades de programação" },
    { name: "habilidades de programação e planejamento" },
    { name: "habilidades de programação orientada a objeto" },
    { name: "habilidades de projeto conceitual" },
    { name: "habilidades de raciocínio" },
    { name: "habilidades de redes sociais" },
    { name: "habilidades de relações públicas" },
    { name: "habilidades de ser capaz de comunicar" },
    { name: "habilidades de serviços de análise" },
    { name: "Habilidades de supervisão" },
    { name: "habilidades de supervisão e formação" },
    { name: "habilidades de telefone" },
    { name: "habilidades de tomada de decisão" },
    { name: "habilidades de trabalho em equipe e liderança" },
    { name: "habilidades de trabalho em equipe habilidades de precisão" },
    { name: "habilidades de trabalho em grupo" },
    { name: "habilidades de treinamento" },
    { name: "habilidades de vendas por telefone" },
    { name: "Habilidades detalhadas no setor administrativo" },
    { name: "habilidades e capacidade de comunicar" },
    { name: "habilidades e na formação produzindo" },
    { name: "habilidades educacionais" },
    { name: "habilidades educacionais e de cuidados" },
    { name: "habilidades em formação em investigação" },
    { name: "habilidades em motivação e treinamento" },
    { name: "Habilidades focadas em análise estatistica" },
    { name: "habilidades gerenciais" },
    { name: "habilidades gerenciais e de liderança" },
    { name: "habilidades gerenciais e motivacionais" },
    { name: "habilidades interpessoais" },
    { name: "habilidades na formação" },
    { name: "habilidades orais" },
    { name: "habilidades organizacionais" },
    { name: "habilidades organizacionais conceituais" },
    { name: "habilidades organizacionais e administrativos" },
    { name: "habilidades organizacionais e analíticas" },
    { name: "habilidades para comunicar eficazmente" },
    { name: "habilidades para resolver problemas" },
    { name: "habilidades para resolver problemas analíticos" },
    { name: "habilidades planningcoordinating" },
    { name: "habilidades resolução de problemas" },
    { name: "habilidades sociais" },
    { name: "habilidades timemanagement e comunicação" },
    { name: "habilidades timemanagement e negociação" },
    { name: "habilidades tomada de decisão" },
    { name: "habilidades verbais" },
    { name: "habilidades voltados cliente" },
    { name: "honestidade" },
    { name: "honesto" },
    { name: "hospitaleiro" },
    { name: "humor" },
    { name: "imaginação" },
    { name: "imaginação criativa" },
    { name: "incentivar e facilitar a inovação" },
    { name: "independente" },
    { name: "influenciando e habilidades de negociação" },
    { name: "influenciando habilidades" },
    { name: "ingenuidade" },
    { name: "iniciativa" },
    { name: "iniciativa disciplina auto" },
    { name: "iniciativa e pensamento" },
    { name: "iniciativa e pensamento criativo" },
    { name: "iniciativa e resultado impulsionado" },
    { name: "iniciativa e resultados impulsionada" },
    { name: "iniciativa orientada" },
    { name: "iniciativa pessoa" },
    { name: "iniciativa própria" },
    { name: "iniciativa uma pessoa" },
    { name: "innovationthe" },
    { name: "inovação" },
    { name: "inovação e habilidades" },
    { name: "inovação incentivando" },
    { name: "Inovativa" },
    { name: "inspirado" },
    { name: "integridade" },
    { name: "integridade pessoal" },
    { name: "inteligente" },
    { name: "interação da equipe" },
    { name: "interação da equipe e habilidades interpessoais" },
    { name: "interesse e desejo de aprender" },
    { name: "interesse para aprender" },
    { name: "jogador da equipe" },
    { name: "jogador da equipe e trabalho" },
    { name: "julgamento" },
    { name: "julgamento de negócios som" },
    { name: "julgamento e habilidades" },
    { name: "julgamento e habilidades de tomada de decisão" },
    { name: "legais" },
    { name: "líder" },
    { name: "líder da equipe de viagens de negócios" },
    { name: "líder de programa de negócios" },
    { name: "Lider do Time" },
    { name: "Liderança" },
    { name: "liderança com a capacidade" },
    { name: "lógico" },
    { name: "madura e personalidade extrovertida" },
    { name: "maduro" },
    { name: "maleável" },
    { name: "maneira" },
    { name: "maneira analítica de pensar" },
    { name: "maneira profissional" },
    { name: "Maneira sistemática" },
    { name: "maturidade" },
    { name: "membro da equipe" },
    { name: "membros da equipe de trabalho" },
    { name: "Mentalidade analitica a fundo" },
    { name: "mentalidade de serviço" },
    { name: "mente aberta" },
    { name: "mente analítica" },
    { name: "mentoring e coaching habilidades" },
    { name: "mentoring habilidades" },
    { name: "metódico" },
    { name: "modo discreto mas firme" },
    { name: "monitoramento de algumas habilidades unix" },
    { name: "monitoramento de ferramentas de script habilidades" },
    { name: "monitoramento de habilidades" },
    { name: "monitoramento de relatórios competências-chave" },
    { name: "monitoramento e habilidades analíticas" },
    { name: "monitoramento e relatórios habilidades" },
    { name: "motivação" },
    { name: "motivado" },
    { name: "motivando" },
    { name: "multitarefa detalhe orientado" },
    { name: "multitarefa habilidades" },
    { name: "multitask orientada" },
    { name: "natureza entusiasta e personalidade" },
    { name: "negociação e habilidades de influenciar" },
    { name: "negociador" },
    { name: "negociador de vendas qualificados" },
    { name: "negociador hábil" },
    { name: "negociador negociador" },
    { name: "nível de auto-motivação" },
    { name: "nível de motivação" },
    { name: "nível de motivação pessoal" },
    { name: "nível gerencial com capacidade" },
    { name: "normas e integridade pessoal" },
    { name: "o desejo de ter sucesso e aprender" },
    { name: "objetivo orientado" },
    { name: "organizacional" },
    { name: "organizado" },
    { name: "organizador" },
    { name: "organizando habilidades" },
    { name: "orientação de aprendizagem cliente" },
    { name: "orientação de serviço do consumidor" },
    { name: "Orientação dos resultados" },
    { name: "orientação para o cliente" },
    { name: "orientação para o cliente e qualidade" },
    { name: "orientação para o serviço cliente" },
    { name: "orientação resolução de problemas" },
    { name: "orientação resultado" },
    { name: "orientação resultados accionado" },
    { name: "orientada a serviços mentalidade" },
    { name: "orientada para resultados" },
    { name: "orientadosa habilidades de design" },
    { name: "originalidade" },
    { name: "os membros da equipe e do trabalho" },
    { name: "ouvir boa capacidade de motivação" },
    { name: "paciência" },
    { name: "paciente" },
    { name: "paciente paciente" },
    { name: "padrões éticos" },
    { name: "paixão" },
    { name: "para multitarefa" },
    { name: "para priorizar e multitarefa" },
    { name: "pastor de" },
    { name: "pensamento abstrato" },
    { name: "pensamento analítico" },
    { name: "pensamento analítico e lógico" },
    { name: "pensamento conceitual" },
    { name: "pensamento criativo" },
    { name: "pensamento criativo e estratégico" },
    { name: "pensamento criativo e habilidades colaborativas" },
    { name: "pensamento criativo e habilidades conceituais" },
    { name: "pensamento criativo e para a frente" },
    { name: "pensamento crítico" },
    { name: "pensamento crítico e criativo skillshighly" },
    { name: "pensamento e planejamento estratégico" },
    { name: "pensamento estratégico" },
    { name: "pensamento inovador" },
    { name: "pensamento inovador e para a frente" },
    { name: "peopleempathy" },
    { name: "personagem" },
    { name: "personalidade alegre" },
    { name: "personalidade amigável" },
    { name: "personalidade amigável e de saída" },
    { name: "personalidade animada e sociável" },
    { name: "personalidade ativa e  fácil de lidar" },
    { name: "personalidade confiante" },
    { name: "personalidade confiante e extrovertido" },
    { name: "personalidade dinâmica" },
    { name: "personalidade e habilidades de pessoas" },
    { name: "personalidade entusiasta" },
    { name: "personalidade entusiasta e determinado" },
    { name: "personalidade excelentes habilidades de comunicação" },
    { name: "personalidade excelentes habilidades interpessoais" },
    { name: "personalidade extrovertida" },
    { name: "personalidade extrovertida confiante" },
    { name: "personalidade forte confiante" },
    { name: "personalidade habilidades organizacionais eficazes" },
    { name: "personalidade líder da equipe" },
    { name: "personalidade madura" },
    { name: "personalidade pessoa sociável" },
    { name: "personalidade profissional" },
    { name: "personalidade responsável e resultsdriven" },
    { name: "personalidade sociável" },
    { name: "personalidade viva" },
    { name: "Perspectiva internacional" },
    { name: "Pessoa ativa" },
    { name: "pessoa ativa para vendas" },
    { name: "pessoa dedicada" },
    { name: "pessoa dinâmica" },
    { name: "pessoa dinâmica e conduzido" },
    { name: "pessoa organizada e meticulosa" },
    { name: "pessoa organizada e positiva" },
    { name: "pessoa responsável" },
    { name: "pessoa trabalhadora" },
    { name: "pessoal e de gestão" },
    { name: "pessoas com essas habilidades" },
    { name: "pessoas com orientada para o cliente" },
    { name: "pessoas e gestão do tempo" },
    { name: "Pessoas orientadas" },
    { name: "planejamento estratégico" },
    { name: "pontual" },
    { name: "pontualidade" },
    { name: "positivo" },
    { name: "positivo e atitude entusiasta" },
    { name: "positivo pode fazer a atitude" },
    { name: "prático" },
    { name: "prazo orientada" },
    { name: "pre reunião prazos acordados" },
    { name: "precisão" },
    { name: "precisão em seu trabalho" },
    { name: "precisão em seus trabalhos diarios" },
    { name: "precisão em todo o trabalho" },
    { name: "precisão no seu trabalho" },
    { name: "preciso" },
    { name: "pró-ativa pró-ativa" },
    { name: "proativo" },
    { name: "proativo na abordagem" },
    { name: "procedimentos corretos de relatórios" },
    { name: "productiveefficient" },
    { name: "produtivo" },
    { name: "profissional" },
    { name: "profissional com apresentação forte" },
    { name: "profissionalismo" },
    { name: "programas de aprendizagem de competências essenciais" },
    { name: "projetar e escrever" },
    { name: "pronto" },
    { name: "qualidade importasse" },
    { name: "querendo aprender" },
    { name: "quotationproposal escrevendo habilidades de vendas fortes" },
    { name: "rápido para aprender" },
    { name: "relacionamento com o cliente" },
    { name: "relações humanas" },
    { name: "relatando fortes habilidades de coordenação" },
    { name: "relatórios corretos" },
    { name: "relatórios EPI correto" },
    { name: "resolução de problemas e atitude cando" },
    { name: "resolução de problemas e atitude responsável" },
    { name: "resolução de problemas e habilidades analíticas" },
    { name: "resolução de problemas e habilidades organizacionais" },
    { name: "respeito dos seus colegas" },
    { name: "respeito pela diversidade" },
    { name: "respeito pelos colegas" },
    { name: "respeitoso" },
    { name: "responsabilidade" },
    { name: "responsável" },
    { name: "responsável pessoa que entrega" },
    { name: "rigoroso" },
    { name: "seja criativo" },
    { name: "selfdevelopmentselflearning" },
    { name: "selflearningdevelopment" },
    { name: "sensibilidade" },
    { name: "sensibilidade cultural" },
    { name: "sensibilização para a segurança auto-disciplinado" },
    { name: "senso de ética nos negócios" },
    { name: "senso de responsabilidade" },
    { name: "ser  criativo" },
    { name: "ser inovador e criativo" },
    { name: "serviço de orientação para o cliente" },
    { name: "simpatia" },
    { name: "sistemático" },
    { name: "skillsability para informar e persuadir" },
    { name: "social e habilidades interpessoais" },
    { name: "sociável" },
    { name: "Solução de problemas" },
    { name: "solução orientada" },
    { name: "solução orientedyou" },
    { name: "solucionador de problema" },
    { name: "specificationsense de responsabilidade" },
    { name: "talento criativo e imaginação" },
    { name: "talentoso" },
    { name: "tarefas domésticas as habilidades" },
    { name: "tato" },
    { name: "tato e forma diplomática" },
    { name: "tato e forma discreta" },
    { name: "time orientado" },
    { name: "tolerância" },
    { name: "tolerante" },
    { name: "toma decisões oportunas" },
    { name: "tomar a iniciativa" },
    { name: "tomar a iniciativa de chumbo" },
    { name: "tomar decisões" },
    { name: "tomar decisões rápidas precisas" },
    { name: "tomar iniciativa" },
    { name: "trabalha duro" },
    { name: "trabalha em colaboração" },
    { name: "trabalhador" },
    { name: "trabalhador equipe" },
    { name: "trabalhador equipe com compromisso" },
    { name: "trabalhador independente" },
    { name: "trabalhador vida independente" },
    { name: "trabalhando duro e pessoa conduzido" },
    { name: "trabalhar bem em equipe" },
    { name: "trabalhar com prazos de pressão" },
    { name: "trabalhar de forma colaborativa" },
    { name: "trabalhar horas irregulares" },
    { name: "trabalhar horas irregulares ocasionais" },
    { name: "Trabalhar sob pressão" },
    { name: "trabalho dos outros em uma equipe pequena" },
    { name: "trabalho em alta pressão" },
    { name: "trabalho em equipe" },
    { name: "trabalho em equipe e habilidades de comunicação" },
    { name: "trabalho em uma equipe pequena" },
    { name: "trabalho sob pressão extrema" },
    { name: "trabalho sob stress" },
    { name: "treinamento" },
    { name: "treinamento de habilidades" },
    { name: "treinamento de habilidades habilidades de coaching" },
    { name: "treinamento e habilidades motivacionais" },
    { name: "vendas impulsionado" },
    { name: "verbais e habilidades de comunicação" },
    { name: "verbal e escrita" },
    { name: "verbal habilidades de comunicação escrita" },
    { name: "versatilidade" },
    { name: "vigoroso" },
    { name: "visão de futuro" },
    { name: "visão de futuro progressiva" },
    { name: "visão estratégica" },
    { name: "voltada para resultados" },
    { name: "vontade de aprender" },
    { name: "vontade e capacidade para ouvir" },
];